sudo: false
language: python
python:
- 3.4
- 3.5
- 3.6
- 2.7
install:
- pip install tox-travis
script: tox

deploy:
  provider: pypi
  user: elviejokike
  password:
    secure: PRMlVIUEwgZpGnZ5IIe5e915NecIv/+H8pShcfP42p0+8BuoqTGK4P6BF70ORz1L3jKDwXDjfnztq45EFTH+5zn1QUoLBF3v/qQ9zPpydh0POioD7Y11+LHJNxThwmOG9VRMkfGWbiW8s6Ufwi3yh3CuzCcxA8Uq9tOaBzXN4G6nf0bV7GJemdwS2a6d4ja4hhpxgXcgKQLUxKKZbCW7btOOECiO6BJs+4aPoiI/zEHD8xt1CT0YYF9chvzUJXFO/a+rRTJmnyaz2mrnvTOlxfVAynM6WWfN63uRWmPwTHDCRGLHz8Sy80uQEOZwprfY5vIpwN06mfxeEXJ2yo6HT2D39iv2zXwkCxXhSIT3ZYjvKRhN82iLAEtfsN5XhlPiEG1uy1uzPWyXwaOtIITyfLRfNHEbJ+AO9VVuT4g+I1vGVQpo0AeUWpK85oX0JFHbXl3eBhPe5xwPy+ecXgeYKLGM5oon1MEWJLXeB3QMTg4s4m+TLr2azMOMJGDXtox90umQfDgCYls90w5lmuiB7aajOAM0iw2cGYug5thnB0l8th8NeIJ8jH3/FUjOG6VRzPqvSpEDLHGvvGK3weUYjHxogcV1WilfCm24WEePUxLKp1w9kEVQu88gtBlgqJ0bWZvoqtZQZ6nfe6R5LsiUA3Nh9L0xqQ3yPqsyuti4Q8k=
  on:
    branch: master
    tags: true
    distributions: sdist bdist_wheel
    repo: elviejokike/flask-eureka