sudo: false
language: python
python:
- 3.4
- 3.5
- 3.6
- 2.7
install:
- pip install tox-travis
script: tox
deploy:
  provider: pypi
  user: elviejokike
  password:
    secure: SERTcUcPl08cyOM5rXEbTzpekapNmFISQQ000XWrzvG+S5ke+6vU2Qlyimw3auIPeLxU2dniz95oGsagDTcIGLqlU997UbeNraxj/IMMzndN+6DDTby3OZtVL2UEWvv9BZMD85B9n1C4Vi4jEfV0dJT72w2Kd+8wfccNBG4yzGldc11/3ncSIptItGg/H0VjQ5FVwDe+OGxfNDyI9S0uXiC7Xv18a0rpz51KL4NtxXRlhZEHtENlfMMThhiWf5mfmWYlpRqqEYbf6zFvqnLSEcich/dEU/ULi2LEwMuUCekmwhLWSu1d+MQyJjfXsP7wPonMSB/WcjVxRbKCg4l3XT5eRB9UV/y2ZeZ69TN+1bVXrezg9g37y/qVq/N5nswCCPm81wjHT8cH5iPPTpCR8H7wovVsDF2cQ71nO7sObdF3IDgn+IdsYNmHp8lCnaexn3NBadmEBsgUcsydR4rHGCW6LVLDiW9287xSPfjtRbZJdMYVX9wM/MPTJ8yxIYVkpHcAGSAF3Zgaf1dOkM/dgGrwgWr4UV6wvSFBJ3wni+Gjtn22ANSo15O79FvhJ+1HZgET4dvhgfFiT3fNblTlV5YtMBP6Um+cosBIrniL8SEhjrd07JKV6KCqlFQEVt1WcIBuY3brEVnH2dyZJsmHSUcZWOkKrXfpy/tZadvCEJA=
  on:
    branch: master
    tags: true
    distributions: sdist bdist_wheel
    repo: elviejokike/flask-eureka
