sudo: false
language: python
python:
- 3.4
- 3.5
- 3.6
install:
- pip install tox-travis
script:
- tox
deploy:
  provider: pypi
  user: elviejokike
  on:
    repo: elviejokike/flask-eureka
    tags: true
  password:
    secure: N9rK9JVxmdCpexQTYeASmZA4KP9faWadsHL+WAiUx+WCB2egSFnsgHQPHi/Jn/pPPaphb0dY0zYUbToaPMEponxaZwOIAFn3a7lqT+kLmoIBqPHGM0+mD7iNTdxrN4tSwbgSpOqHQG9VzMEdMMEOF23LQ8kDgreAfyydHKF+WOXmLNEZ03uiw5F2OV/bWudilBK1X+h9/b70+WSlVUS2kL7wRcMfl4rVvgicFeZGvzOv0Nu8A0aaF9yrQ7hDNRTJ5vEDFYlSYjyG29oXcdNw0c65GlcAjPZJRZpMfNIKnoJ9hYdjY/CK+HfmxbqbJOt76CocsnsgGFkqNC5Uy8oOuGSROhR40ukQcbNxJdoGCSqx7dWS5tcRd1Cr+V8MzzU1OZmVF7eKiBdencg+SxqVZliig/QDMBubdCiuxnInY9tN3sPuk7jKMyWoGGPj9senzR7PZv/yGyu1zB1fIwyaVY5cVzFVp+vkCD9m4ZaxrXbfpZlujFifqFuHlPqJZE1JmnTD7/m6wNNgMthmUPatF6s8EvHFXkkunQSgcYw3apEJJFQ5xDQkU/rLCGLDyVPt8BHc9XKmYSrQApttGAClWT/QdE60Kuq9NLa0aXw+W3EN31Aon86jyjnACHxWmN6zFQIc0AO+gBSHSyWqf+6nYVeMp0VM5m2ZgvvILj9BC20=
